import { createContext, useContext, useState, ReactNode } from 'react';

export type LangCode = 'en' | 'hi' | 'pa' | 'bn' | 'or' | 'kn' | 'ta' | 'te' | 'mr' | 'gu';

export const LANGUAGES: { code: LangCode; label: string; native: string }[] = [
  { code: 'en', label: 'English',   native: 'English' },
  { code: 'hi', label: 'Hindi',     native: 'हिन्दी' },
  { code: 'pa', label: 'Punjabi',   native: 'ਪੰਜਾਬੀ' },
  { code: 'bn', label: 'Bengali',   native: 'বাংলা' },
  { code: 'or', label: 'Odia',      native: 'ଓଡ଼ିଆ' },
  { code: 'kn', label: 'Kannada',   native: 'ಕನ್ನಡ' },
  { code: 'ta', label: 'Tamil',     native: 'தமிழ்' },
  { code: 'te', label: 'Telugu',    native: 'తెలుగు' },
  { code: 'mr', label: 'Marathi',   native: 'मराठी' },
  { code: 'gu', label: 'Gujarati',  native: 'ગુજરાતી' },
];

const translations: Record<LangCode, Record<string, string>> = {
  en: {
    home: 'Home', my_bookings: 'My Bookings', profile: 'Profile', dashboard: 'Dashboard',
    my_profile: 'My Profile', logout: 'Logout', notifications: 'Notifications',
    search_placeholder: 'Search for services or karigars...',
    book_now: 'Book Now', available: 'Available', busy: 'Busy', offline: 'Offline',
    verified: 'Verified', top_rated: 'Top Rated', rating: 'Rating',
    request_sent: 'Request Sent', accepted: 'Accepted', completed: 'Completed',
    pending: 'Pending', rejected: 'Rejected', cancelled: 'Cancelled',
    select_date: 'Select Date', select_time: 'Select Time Slot',
    confirm_booking: 'Confirm Booking', cancel: 'Cancel',
    no_results: 'No results found', loading: 'Loading...',
    chatbot_greeting: 'Namaste! I\'m KarigarHub AI',
    chatbot_subtitle: 'Ask me anything about our services',
    ask_anything: 'Ask anything...', send: 'Send',
    find_electrician: '🔧 Find an electrician', plumbing_help: '🚿 Plumbing help',
    how_to_book: '📋 How to book?', pricing_info: '💰 Pricing info',
    years_exp: 'years exp', km_away: 'km away', jobs_done: 'jobs done',
    per_hour: '/hr', reviews: 'Reviews', experience: 'Experience',
    location: 'Location', description: 'Description', skills: 'Skills',
    earnings: 'Earnings', completed_jobs: 'Completed Jobs',
    login: 'Login', signup: 'Sign Up', customer: 'Customer', worker: 'Worker',
    landing_title: 'Find Trusted Skilled Workers Near You',
    landing_subtitle: 'Connect with verified karigars for all your home service needs',
    get_started: 'Get Started',
    mark_completed: 'Mark Completed', rate_karigar: 'Rate Karigar',
    voice_input: 'Voice Input', stop_recording: 'Stop',
  },
  hi: {
    home: 'होम', my_bookings: 'मेरी बुकिंग', profile: 'प्रोफ़ाइल', dashboard: 'डैशबोर्ड',
    my_profile: 'मेरी प्रोफ़ाइल', logout: 'लॉग आउट', notifications: 'सूचनाएं',
    search_placeholder: 'सेवाएं या कारीगर खोजें...',
    book_now: 'अभी बुक करें', available: 'उपलब्ध', busy: 'व्यस्त', offline: 'ऑफ़लाइन',
    verified: 'सत्यापित', top_rated: 'टॉप रेटेड', rating: 'रेटिंग',
    request_sent: 'अनुरोध भेजा', accepted: 'स्वीकृत', completed: 'पूर्ण',
    pending: 'लंबित', rejected: 'अस्वीकृत', cancelled: 'रद्द',
    select_date: 'तारीख चुनें', select_time: 'समय चुनें',
    confirm_booking: 'बुकिंग पुष्टि करें', cancel: 'रद्द करें',
    no_results: 'कोई परिणाम नहीं', loading: 'लोड हो रहा है...',
    chatbot_greeting: 'नमस्ते! मैं KarigarHub AI हूं',
    chatbot_subtitle: 'हमारी सेवाओं के बारे में कुछ भी पूछें',
    ask_anything: 'कुछ भी पूछें...', send: 'भेजें',
    find_electrician: '🔧 इलेक्ट्रीशियन खोजें', plumbing_help: '🚿 प्लंबिंग सहायता',
    how_to_book: '📋 बुकिंग कैसे करें?', pricing_info: '💰 मूल्य जानकारी',
    years_exp: 'साल का अनुभव', km_away: 'किमी दूर', jobs_done: 'काम पूरे',
    per_hour: '/घंटा', reviews: 'समीक्षाएं', experience: 'अनुभव',
    location: 'स्थान', description: 'विवरण', skills: 'कौशल',
    earnings: 'कमाई', completed_jobs: 'पूर्ण काम',
    login: 'लॉगिन', signup: 'साइन अप', customer: 'ग्राहक', worker: 'कारीगर',
    landing_title: 'अपने पास विश्वसनीय कारीगर खोजें',
    landing_subtitle: 'सभी घरेलू सेवाओं के लिए सत्यापित कारीगरों से जुड़ें',
    get_started: 'शुरू करें',
    mark_completed: 'पूर्ण चिह्नित करें', rate_karigar: 'कारीगर को रेट करें',
    voice_input: 'आवाज़ इनपुट', stop_recording: 'रुकें',
  },
  pa: {
    home: 'ਘਰ', my_bookings: 'ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ', profile: 'ਪ੍ਰੋਫਾਈਲ', dashboard: 'ਡੈਸ਼ਬੋਰਡ',
    my_profile: 'ਮੇਰੀ ਪ੍ਰੋਫਾਈਲ', logout: 'ਲੌਗ ਆਊਟ', notifications: 'ਸੂਚਨਾਵਾਂ',
    search_placeholder: 'ਸੇਵਾਵਾਂ ਜਾਂ ਕਾਰੀਗਰ ਖੋਜੋ...',
    book_now: 'ਹੁਣੇ ਬੁੱਕ ਕਰੋ', available: 'ਉਪਲਬਧ', busy: 'ਰੁੱਝਿਆ', offline: 'ਔਫਲਾਈਨ',
    verified: 'ਪ੍ਰਮਾਣਿਤ', top_rated: 'ਟੌਪ ਰੇਟਿਡ', rating: 'ਰੇਟਿੰਗ',
    request_sent: 'ਬੇਨਤੀ ਭੇਜੀ', accepted: 'ਸਵੀਕਾਰ', completed: 'ਪੂਰਾ',
    pending: 'ਬਕਾਇਆ', rejected: 'ਰੱਦ', cancelled: 'ਰੱਦ ਕੀਤਾ',
    select_date: 'ਤਾਰੀਖ ਚੁਣੋ', select_time: 'ਸਮਾਂ ਚੁਣੋ',
    confirm_booking: 'ਬੁਕਿੰਗ ਪੁਸ਼ਟੀ ਕਰੋ', cancel: 'ਰੱਦ ਕਰੋ',
    no_results: 'ਕੋਈ ਨਤੀਜੇ ਨਹੀਂ', loading: 'ਲੋਡ ਹੋ ਰਿਹਾ...',
    chatbot_greeting: 'ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ KarigarHub AI ਹਾਂ',
    chatbot_subtitle: 'ਸਾਡੀਆਂ ਸੇਵਾਵਾਂ ਬਾਰੇ ਕੁਝ ਵੀ ਪੁੱਛੋ',
    ask_anything: 'ਕੁਝ ਵੀ ਪੁੱਛੋ...', send: 'ਭੇਜੋ',
    find_electrician: '🔧 ਇਲੈਕਟ੍ਰੀਸ਼ੀਅਨ ਲੱਭੋ', plumbing_help: '🚿 ਪਲੰਬਿੰਗ ਮਦਦ',
    how_to_book: '📋 ਬੁਕਿੰਗ ਕਿਵੇਂ ਕਰੀਏ?', pricing_info: '💰 ਕੀਮਤ ਜਾਣਕਾਰੀ',
    years_exp: 'ਸਾਲ ਤਜਰਬਾ', km_away: 'ਕਿਮੀ ਦੂਰ', jobs_done: 'ਕੰਮ ਪੂਰੇ',
    per_hour: '/ਘੰਟਾ', reviews: 'ਸਮੀਖਿਆਵਾਂ', experience: 'ਤਜਰਬਾ',
    location: 'ਸਥਾਨ', description: 'ਵੇਰਵਾ', skills: 'ਹੁਨਰ',
    earnings: 'ਕਮਾਈ', completed_jobs: 'ਪੂਰੇ ਕੰਮ',
    login: 'ਲੌਗਇਨ', signup: 'ਸਾਈਨ ਅੱਪ', customer: 'ਗਾਹਕ', worker: 'ਕਾਰੀਗਰ',
    landing_title: 'ਆਪਣੇ ਨੇੜੇ ਭਰੋਸੇਯੋਗ ਕਾਰੀਗਰ ਲੱਭੋ',
    landing_subtitle: 'ਸਾਰੀਆਂ ਘਰੇਲੂ ਸੇਵਾਵਾਂ ਲਈ ਪ੍ਰਮਾਣਿਤ ਕਾਰੀਗਰਾਂ ਨਾਲ ਜੁੜੋ',
    get_started: 'ਸ਼ੁਰੂ ਕਰੋ',
    mark_completed: 'ਪੂਰਾ ਮਾਰਕ ਕਰੋ', rate_karigar: 'ਕਾਰੀਗਰ ਨੂੰ ਰੇਟ ਕਰੋ',
    voice_input: 'ਅਵਾਜ਼ ਇਨਪੁਟ', stop_recording: 'ਰੁਕੋ',
  },
  bn: {
    home: 'হোম', my_bookings: 'আমার বুকিং', profile: 'প্রোফাইল', dashboard: 'ড্যাশবোর্ড',
    my_profile: 'আমার প্রোফাইল', logout: 'লগ আউট', notifications: 'বিজ্ঞপ্তি',
    search_placeholder: 'সেবা বা কারিগর খুঁজুন...',
    book_now: 'এখনই বুক করুন', available: 'উপলব্ধ', busy: 'ব্যস্ত', offline: 'অফলাইন',
    verified: 'যাচাইকৃত', top_rated: 'শীর্ষ রেটেড', rating: 'রেটিং',
    request_sent: 'অনুরোধ পাঠানো হয়েছে', accepted: 'গৃহীত', completed: 'সম্পন্ন',
    pending: 'বিচারাধীন', rejected: 'প্রত্যাখ্যাত', cancelled: 'বাতিল',
    select_date: 'তারিখ নির্বাচন করুন', select_time: 'সময় নির্বাচন করুন',
    confirm_booking: 'বুকিং নিশ্চিত করুন', cancel: 'বাতিল করুন',
    no_results: 'কোনো ফলাফল নেই', loading: 'লোড হচ্ছে...',
    chatbot_greeting: 'নমস্কার! আমি KarigarHub AI',
    chatbot_subtitle: 'আমাদের সেবা সম্পর্কে যেকোনো প্রশ্ন করুন',
    ask_anything: 'যেকোনো কিছু জিজ্ঞাসা করুন...', send: 'পাঠান',
    find_electrician: '🔧 ইলেকট্রিশিয়ান খুঁজুন', plumbing_help: '🚿 প্লাম্বিং সাহায্য',
    how_to_book: '📋 কিভাবে বুক করবেন?', pricing_info: '💰 মূল্য তথ্য',
    years_exp: 'বছরের অভিজ্ঞতা', km_away: 'কিমি দূরে', jobs_done: 'কাজ সম্পন্ন',
    per_hour: '/ঘণ্টা', reviews: 'পর্যালোচনা', experience: 'অভিজ্ঞতা',
    location: 'অবস্থান', description: 'বিবরণ', skills: 'দক্ষতা',
    earnings: 'আয়', completed_jobs: 'সম্পন্ন কাজ',
    login: 'লগইন', signup: 'সাইন আপ', customer: 'গ্রাহক', worker: 'কারিগর',
    landing_title: 'আপনার কাছে বিশ্বস্ত কারিগর খুঁজুন',
    landing_subtitle: 'সব ঘরোয়া সেবার জন্য যাচাইকৃত কারিগরদের সাথে যুক্ত হন',
    get_started: 'শুরু করুন',
    mark_completed: 'সম্পন্ন চিহ্নিত করুন', rate_karigar: 'কারিগরকে রেট করুন',
    voice_input: 'ভয়েস ইনপুট', stop_recording: 'থামুন',
  },
  or: {
    home: 'ହୋମ', my_bookings: 'ମୋ ବୁକିଂ', profile: 'ପ୍ରୋଫାଇଲ', dashboard: 'ଡ୍ୟାସବୋର୍ଡ',
    my_profile: 'ମୋ ପ୍ରୋଫାଇଲ', logout: 'ଲଗଆଉଟ', notifications: 'ସୂଚନା',
    search_placeholder: 'ସେବା ବା କାରିଗର ଖୋଜନ୍ତୁ...',
    book_now: 'ଏବେ ବୁକ କରନ୍ତୁ', available: 'ଉପଲବ୍ଧ', busy: 'ବ୍ୟସ୍ତ', offline: 'ଅଫଲାଇନ',
    verified: 'ଯାଞ୍ଚ ହୋଇଛି', top_rated: 'ଶ୍ରେଷ୍ଠ ରେଟିଂ', rating: 'ରେଟିଂ',
    request_sent: 'ଅନୁରୋଧ ପଠାଯାଇଛି', accepted: 'ଗ୍ରହଣ', completed: 'ସମ୍ପୂର୍ଣ୍ଣ',
    pending: 'ବିଚାରାଧୀନ', rejected: 'ପ୍ରତ୍ୟାଖ୍ୟାନ', cancelled: 'ବାତିଲ',
    select_date: 'ତାରିଖ ବାଛନ୍ତୁ', select_time: 'ସମୟ ବାଛନ୍ତୁ',
    confirm_booking: 'ବୁକିଂ ନିଶ୍ଚିତ କରନ୍ତୁ', cancel: 'ବାତିଲ କରନ୍ତୁ',
    no_results: 'କୌଣସି ଫଳାଫଳ ନାହିଁ', loading: 'ଲୋଡ ହେଉଛି...',
    chatbot_greeting: 'ନମସ୍କାର! ମୁଁ KarigarHub AI',
    chatbot_subtitle: 'ଆମ ସେବା ବିଷୟରେ କିଛି ପଚାରନ୍ତୁ',
    ask_anything: 'କିଛି ପଚାରନ୍ତୁ...', send: 'ପଠାନ୍ତୁ',
    find_electrician: '🔧 ଇଲେକ୍ଟ୍ରିସିଆନ ଖୋଜନ୍ତୁ', plumbing_help: '🚿 ପ୍ଲମ୍ବିଂ ସାହାଯ୍ୟ',
    how_to_book: '📋 ବୁକିଂ କିପରି?', pricing_info: '💰 ମୂଲ୍ୟ ତଥ୍ୟ',
    years_exp: 'ବର୍ଷ ଅଭିଜ୍ଞତା', km_away: 'କିମି ଦୂର', jobs_done: 'କାମ ସମ୍ପୂର୍ଣ୍ଣ',
    per_hour: '/ଘଣ୍ଟା', reviews: 'ସମୀକ୍ଷା', experience: 'ଅଭିଜ୍ଞତା',
    location: 'ସ୍ଥାନ', description: 'ବିବରଣ', skills: 'ଦକ୍ଷତା',
    earnings: 'ଆୟ', completed_jobs: 'ସମ୍ପୂର୍ଣ୍ଣ କାମ',
    login: 'ଲଗଇନ', signup: 'ସାଇନ ଅପ', customer: 'ଗ୍ରାହକ', worker: 'କାରିଗର',
    landing_title: 'ଆପଣଙ୍କ ନିକଟରେ ବିଶ୍ୱସ୍ତ କାରିଗର ଖୋଜନ୍ତୁ',
    landing_subtitle: 'ସମସ୍ତ ଘରୋଇ ସେବା ପାଇଁ ଯାଞ୍ଚ ହୋଇଥିବା କାରିଗରଙ୍କ ସହ ଯୋଡ଼ି ହୁଅନ୍ତୁ',
    get_started: 'ଆରମ୍ଭ କରନ୍ତୁ',
    mark_completed: 'ସମ୍ପୂର୍ଣ୍ଣ ଚିହ୍ନିତ', rate_karigar: 'କାରିଗରଙ୍କୁ ରେଟ କରନ୍ତୁ',
    voice_input: 'ସ୍ୱର ଇନପୁଟ', stop_recording: 'ବନ୍ଦ',
  },
  kn: {
    home: 'ಮುಖಪುಟ', my_bookings: 'ನನ್ನ ಬುಕಿಂಗ್‌ಗಳು', profile: 'ಪ್ರೊಫೈಲ್', dashboard: 'ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
    my_profile: 'ನನ್ನ ಪ್ರೊಫೈಲ್', logout: 'ಲಾಗ್ ಔಟ್', notifications: 'ಅಧಿಸೂಚನೆಗಳು',
    search_placeholder: 'ಸೇವೆಗಳು ಅಥವಾ ಕಾರಿಗರ ಹುಡುಕಿ...',
    book_now: 'ಈಗ ಬುಕ್ ಮಾಡಿ', available: 'ಲಭ್ಯ', busy: 'ಬ್ಯುಸಿ', offline: 'ಆಫ್‌ಲೈನ್',
    verified: 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ', top_rated: 'ಟಾಪ್ ರೇಟೆಡ್', rating: 'ರೇಟಿಂಗ್',
    request_sent: 'ವಿನಂತಿ ಕಳುಹಿಸಲಾಗಿದೆ', accepted: 'ಸ್ವೀಕರಿಸಲಾಗಿದೆ', completed: 'ಪೂರ್ಣ',
    pending: 'ಬಾಕಿ', rejected: 'ನಿರಾಕರಿಸಲಾಗಿದೆ', cancelled: 'ರದ್ದುಮಾಡಲಾಗಿದೆ',
    select_date: 'ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ', select_time: 'ಸಮಯ ಆಯ್ಕೆಮಾಡಿ',
    confirm_booking: 'ಬುಕಿಂಗ್ ದೃಢೀಕರಿಸಿ', cancel: 'ರದ್ದುಮಾಡಿ',
    no_results: 'ಫಲಿತಾಂಶ ಇಲ್ಲ', loading: 'ಲೋಡ್ ಆಗುತ್ತಿದೆ...',
    chatbot_greeting: 'ನಮಸ್ಕಾರ! ನಾನು KarigarHub AI',
    chatbot_subtitle: 'ನಮ್ಮ ಸೇವೆಗಳ ಬಗ್ಗೆ ಏನಾದರೂ ಕೇಳಿ',
    ask_anything: 'ಏನಾದರೂ ಕೇಳಿ...', send: 'ಕಳುಹಿಸಿ',
    find_electrician: '🔧 ಎಲೆಕ್ಟ್ರೀಶಿಯನ್ ಹುಡುಕಿ', plumbing_help: '🚿 ಪ್ಲಂಬಿಂಗ್ ಸಹಾಯ',
    how_to_book: '📋 ಬುಕ್ ಮಾಡುವುದು ಹೇಗೆ?', pricing_info: '💰 ಬೆಲೆ ಮಾಹಿತಿ',
    years_exp: 'ವರ್ಷ ಅನುಭವ', km_away: 'ಕಿಮೀ ದೂರ', jobs_done: 'ಕೆಲಸ ಪೂರ್ಣ',
    per_hour: '/ಗಂಟೆ', reviews: 'ವಿಮರ್ಶೆಗಳು', experience: 'ಅನುಭವ',
    location: 'ಸ್ಥಳ', description: 'ವಿವರಣೆ', skills: 'ಕೌಶಲ್ಯ',
    earnings: 'ಗಳಿಕೆ', completed_jobs: 'ಪೂರ್ಣ ಕೆಲಸ',
    login: 'ಲಾಗಿನ್', signup: 'ಸೈನ್ ಅಪ್', customer: 'ಗ್ರಾಹಕ', worker: 'ಕಾರಿಗರ',
    landing_title: 'ನಿಮ್ಮ ಹತ್ತಿರ ವಿಶ್ವಾಸಾರ್ಹ ಕಾರಿಗರರನ್ನು ಹುಡುಕಿ',
    landing_subtitle: 'ಎಲ್ಲಾ ಮನೆ ಸೇವೆಗಳಿಗಾಗಿ ಪರಿಶೀಲಿತ ಕಾರಿಗರರೊಂದಿಗೆ ಸಂಪರ್ಕಿಸಿ',
    get_started: 'ಪ್ರಾರಂಭಿಸಿ',
    mark_completed: 'ಪೂರ್ಣ ಗುರುತಿಸಿ', rate_karigar: 'ಕಾರಿಗರ ರೇಟ್ ಮಾಡಿ',
    voice_input: 'ಧ್ವನಿ ಇನ್‌ಪುಟ್', stop_recording: 'ನಿಲ್ಲಿಸಿ',
  },
  ta: {
    home: 'முகப்பு', my_bookings: 'எனது புக்கிங்கள்', profile: 'சுயவிவரம்', dashboard: 'டாஷ்போர்டு',
    my_profile: 'எனது சுயவிவரம்', logout: 'வெளியேறு', notifications: 'அறிவிப்புகள்',
    search_placeholder: 'சேவைகள் அல்லது காரிகர் தேடுங்கள்...',
    book_now: 'இப்போது புக் செய்யுங்கள்', available: 'கிடைக்கிறது', busy: 'பிஸியாக', offline: 'ஆஃப்லைன்',
    verified: 'சரிபார்க்கப்பட்டது', top_rated: 'டாப் ரேட்டிங்', rating: 'ரேட்டிங்',
    request_sent: 'கோரிக்கை அனுப்பப்பட்டது', accepted: 'ஏற்றுக்கொள்ளப்பட்டது', completed: 'நிறைவு',
    pending: 'நிலுவை', rejected: 'நிராகரிக்கப்பட்டது', cancelled: 'ரத்து செய்யப்பட்டது',
    select_date: 'தேதி தேர்வு', select_time: 'நேரம் தேர்வு',
    confirm_booking: 'புக்கிங் உறுதிப்படுத்து', cancel: 'ரத்து செய்',
    no_results: 'முடிவுகள் இல்லை', loading: 'ஏற்றப்படுகிறது...',
    chatbot_greeting: 'வணக்கம்! நான் KarigarHub AI',
    chatbot_subtitle: 'எங்கள் சேவைகள் பற்றி எதையும் கேளுங்கள்',
    ask_anything: 'எதையும் கேளுங்கள்...', send: 'அனுப்பு',
    find_electrician: '🔧 எலக்ட்ரீஷியன் கண்டுபிடி', plumbing_help: '🚿 பிளம்பிங் உதவி',
    how_to_book: '📋 புக் செய்வது எப்படி?', pricing_info: '💰 விலை தகவல்',
    years_exp: 'ஆண்டு அனுபவம்', km_away: 'கிமீ தொலைவு', jobs_done: 'வேலை முடிந்தது',
    per_hour: '/மணி', reviews: 'மதிப்புரைகள்', experience: 'அனுபவம்',
    location: 'இடம்', description: 'விளக்கம்', skills: 'திறன்',
    earnings: 'வருமானம்', completed_jobs: 'முடிந்த வேலைகள்',
    login: 'உள்நுழைவு', signup: 'பதிவு', customer: 'வாடிக்கையாளர்', worker: 'காரிகர்',
    landing_title: 'உங்கள் அருகில் நம்பகமான காரிகர்களைக் கண்டறியுங்கள்',
    landing_subtitle: 'அனைத்து வீட்டு சேவைகளுக்கும் சரிபார்க்கப்பட்ட காரிகர்களுடன் இணையுங்கள்',
    get_started: 'தொடங்குங்கள்',
    mark_completed: 'நிறைவு குறிக்க', rate_karigar: 'காரிகரை மதிப்பிடு',
    voice_input: 'குரல் உள்ளீடு', stop_recording: 'நிறுத்து',
  },
  te: {
    home: 'హోమ్', my_bookings: 'నా బుకింగ్‌లు', profile: 'ప్రొఫైల్', dashboard: 'డాష్‌బోర్డ్',
    my_profile: 'నా ప్రొఫైల్', logout: 'లాగ్ అవుట్', notifications: 'నోటిఫికేషన్లు',
    search_placeholder: 'సేవలు లేదా కారిగర్ వెతకండి...',
    book_now: 'ఇప్పుడు బుక్ చేయండి', available: 'అందుబాటులో', busy: 'బిజీ', offline: 'ఆఫ్‌లైన్',
    verified: 'ధృవీకరించబడింది', top_rated: 'టాప్ రేటెడ్', rating: 'రేటింగ్',
    request_sent: 'అభ్యర్థన పంపబడింది', accepted: 'ఆమోదించబడింది', completed: 'పూర్తయింది',
    pending: 'పెండింగ్', rejected: 'తిరస్కరించబడింది', cancelled: 'రద్దు చేయబడింది',
    select_date: 'తేదీ ఎంచుకోండి', select_time: 'సమయం ఎంచుకోండి',
    confirm_booking: 'బుకింగ్ నిర్ధారించండి', cancel: 'రద్దు చేయండి',
    no_results: 'ఫలితాలు లేవు', loading: 'లోడ్ అవుతోంది...',
    chatbot_greeting: 'నమస్కారం! నేను KarigarHub AI',
    chatbot_subtitle: 'మా సేవల గురించి ఏదైనా అడగండి',
    ask_anything: 'ఏదైనా అడగండి...', send: 'పంపు',
    find_electrician: '🔧 ఎలక్ట్రీషియన్ కనుగొనండి', plumbing_help: '🚿 ప్లంబింగ్ సహాయం',
    how_to_book: '📋 బుక్ చేయడం ఎలా?', pricing_info: '💰 ధర సమాచారం',
    years_exp: 'సంవత్సరాల అనుభవం', km_away: 'కిమీ దూరం', jobs_done: 'పూర్తి చేసిన పనులు',
    per_hour: '/గంట', reviews: 'సమీక్షలు', experience: 'అనుభవం',
    location: 'స్థానం', description: 'వివరణ', skills: 'నైపుణ్యాలు',
    earnings: 'ఆదాయం', completed_jobs: 'పూర్తి పనులు',
    login: 'లాగిన్', signup: 'సైన్ అప్', customer: 'కస్టమర్', worker: 'కారిగర్',
    landing_title: 'మీ సమీపంలో నమ్మకమైన కారిగర్లను కనుగొనండి',
    landing_subtitle: 'అన్ని గృహ సేవల కోసం ధృవీకరించబడిన కారిగర్లతో అనుసంధానం అవ్వండి',
    get_started: 'ప్రారంభించండి',
    mark_completed: 'పూర్తి గుర్తించు', rate_karigar: 'కారిగర్‌ను రేట్ చేయండి',
    voice_input: 'వాయిస్ ఇన్‌పుట్', stop_recording: 'ఆపు',
  },
  mr: {
    home: 'मुखपृष्ठ', my_bookings: 'माझ्या बुकिंग', profile: 'प्रोफाइल', dashboard: 'डॅशबोर्ड',
    my_profile: 'माझे प्रोफाइल', logout: 'लॉग आउट', notifications: 'सूचना',
    search_placeholder: 'सेवा किंवा कारागीर शोधा...',
    book_now: 'आता बुक करा', available: 'उपलब्ध', busy: 'व्यस्त', offline: 'ऑफलाइन',
    verified: 'सत्यापित', top_rated: 'टॉप रेटेड', rating: 'रेटिंग',
    request_sent: 'विनंती पाठवली', accepted: 'स्वीकृत', completed: 'पूर्ण',
    pending: 'प्रलंबित', rejected: 'नाकारले', cancelled: 'रद्द',
    select_date: 'तारीख निवडा', select_time: 'वेळ निवडा',
    confirm_booking: 'बुकिंग पुष्टी करा', cancel: 'रद्द करा',
    no_results: 'कोणतेही निकाल नाहीत', loading: 'लोड होत आहे...',
    chatbot_greeting: 'नमस्कार! मी KarigarHub AI',
    chatbot_subtitle: 'आमच्या सेवांबद्दल काहीही विचारा',
    ask_anything: 'काहीही विचारा...', send: 'पाठवा',
    find_electrician: '🔧 इलेक्ट्रीशियन शोधा', plumbing_help: '🚿 प्लंबिंग मदत',
    how_to_book: '📋 बुकिंग कसे करावे?', pricing_info: '💰 किंमत माहिती',
    years_exp: 'वर्षे अनुभव', km_away: 'किमी दूर', jobs_done: 'काम पूर्ण',
    per_hour: '/तास', reviews: 'पुनरावलोकने', experience: 'अनुभव',
    location: 'स्थान', description: 'वर्णन', skills: 'कौशल्य',
    earnings: 'कमाई', completed_jobs: 'पूर्ण काम',
    login: 'लॉगिन', signup: 'साइन अप', customer: 'ग्राहक', worker: 'कारागीर',
    landing_title: 'तुमच्या जवळ विश्वासू कारागीर शोधा',
    landing_subtitle: 'सर्व घरगुती सेवांसाठी सत्यापित कारागीरांशी जोडले जा',
    get_started: 'सुरू करा',
    mark_completed: 'पूर्ण चिन्हांकित करा', rate_karigar: 'कारागीरला रेट करा',
    voice_input: 'आवाज इनपुट', stop_recording: 'थांबा',
  },
  gu: {
    home: 'હોમ', my_bookings: 'મારી બુકિંગ', profile: 'પ્રોફાઇલ', dashboard: 'ડેશબોર્ડ',
    my_profile: 'મારી પ્રોફાઇલ', logout: 'લોગ આઉટ', notifications: 'સૂચનાઓ',
    search_placeholder: 'સેવાઓ અથવા કારીગર શોધો...',
    book_now: 'હમણાં બુક કરો', available: 'ઉપલબ્ધ', busy: 'વ્યસ્ત', offline: 'ઓફલાઇન',
    verified: 'ચકાસાયેલ', top_rated: 'ટોપ રેટેડ', rating: 'રેટિંગ',
    request_sent: 'વિનંતી મોકલાઈ', accepted: 'સ્વીકૃત', completed: 'પૂર્ણ',
    pending: 'બાકી', rejected: 'નામંજૂર', cancelled: 'રદ',
    select_date: 'તારીખ પસંદ કરો', select_time: 'સમય પસંદ કરો',
    confirm_booking: 'બુકિંગ પુષ્ટિ કરો', cancel: 'રદ કરો',
    no_results: 'કોઈ પરિણામ નથી', loading: 'લોડ થઈ રહ્યું છે...',
    chatbot_greeting: 'નમસ્તે! હું KarigarHub AI છું',
    chatbot_subtitle: 'અમારી સેવાઓ વિશે કંઈ પણ પૂછો',
    ask_anything: 'કંઈ પણ પૂછો...', send: 'મોકલો',
    find_electrician: '🔧 ઇલેક્ટ્રીશિયન શોધો', plumbing_help: '🚿 પ્લમ્બિંગ મદદ',
    how_to_book: '📋 બુકિંગ કેવી રીતે?', pricing_info: '💰 કિંમત માહિતી',
    years_exp: 'વર્ષ અનુભવ', km_away: 'કિમી દૂર', jobs_done: 'કામ પૂર્ણ',
    per_hour: '/કલાક', reviews: 'સમીક્ષાઓ', experience: 'અનુભવ',
    location: 'સ્થાન', description: 'વર્ણન', skills: 'કૌશલ્ય',
    earnings: 'કમાણી', completed_jobs: 'પૂર્ણ કામ',
    login: 'લોગિન', signup: 'સાઇન અપ', customer: 'ગ્રાહક', worker: 'કારીગર',
    landing_title: 'તમારી નજીક વિશ્વસનીય કારીગર શોધો',
    landing_subtitle: 'બધી ઘરેલુ સેવાઓ માટે ચકાસાયેલ કારીગરો સાથે જોડાઓ',
    get_started: 'શરૂ કરો',
    mark_completed: 'પૂર્ણ ચિહ્નિત કરો', rate_karigar: 'કારીગરને રેટ કરો',
    voice_input: 'અવાજ ઇનપુટ', stop_recording: 'રોકો',
  },
};

type LanguageContextType = {
  lang: LangCode;
  setLang: (l: LangCode) => void;
  t: (key: string) => string;
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<LangCode>(() => {
    const saved = localStorage.getItem('karigarhub-lang');
    return (saved as LangCode) || 'en';
  });

  const changeLang = (l: LangCode) => {
    setLang(l);
    localStorage.setItem('karigarhub-lang', l);
  };

  const t = (key: string): string => {
    return translations[lang]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang: changeLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
};
