// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/search-karigars.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-karigars.ts
var search_karigars_default = defineTool({
  name: "search_karigars",
  title: "Search karigars",
  description: "Search available karigars (skilled workers) by skill, location, availability, and maximum hourly price.",
  inputSchema: {
    skill: z.string().optional().describe("Skill to filter by, e.g. Electrician, Plumber, Carpenter."),
    location: z.string().optional().describe("Location substring to filter by."),
    available_only: z.boolean().optional().describe("Only return karigars marked available."),
    max_price: z.number().optional().describe("Maximum hourly price in INR."),
    limit: z.number().optional().describe("Maximum number of results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ skill, location, available_only, max_price, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("karigars").select("id,name,skill,location,price,rating,review_count,experience,availability,completed_jobs,description").order("rating", { ascending: false }).limit(Math.min(Math.max(limit ?? 10, 1), 50));
    if (skill) query = query.ilike("skill", `%${skill}%`);
    if (location) query = query.ilike("location", `%${location}%`);
    if (available_only) query = query.eq("availability", "available");
    if (typeof max_price === "number") query = query.lte("price", max_price);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { karigars: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_my_bookings_default = defineTool2({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List bookings visible to the signed-in user (as customer or as karigar), optionally filtered by status.",
  inputSchema: {
    status: z2.string().optional().describe("Filter by status, e.g. pending, accepted, completed, cancelled."),
    limit: z2.number().optional().describe("Maximum number of bookings (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select("id,skill,status,date,time,description,customer_name,karigar_name,rating,review,created_at").order("date", { ascending: false }).limit(Math.min(Math.max(limit ?? 20, 1), 100));
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { bookings: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-booking.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var create_booking_default = defineTool3({
  name: "create_booking",
  title: "Create booking",
  description: "Create a booking request with a karigar for the signed-in customer. Use search_karigars first to get a karigar id.",
  inputSchema: {
    karigar_id: z3.string().describe("The karigar's id from search_karigars."),
    date: z3.string().describe("Booking date in YYYY-MM-DD (IST)."),
    time: z3.string().describe("Booking time slot, e.g. 10:00 (IST, hourly between 06:00 and 21:00)."),
    description: z3.string().optional().describe("What needs to be done.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ karigar_id, date, time, description }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: karigar, error: karigarError } = await supabase.from("karigars").select("id,name,skill").eq("id", karigar_id).maybeSingle();
    if (karigarError) return { content: [{ type: "text", text: karigarError.message }], isError: true };
    if (!karigar) return { content: [{ type: "text", text: "Karigar not found" }], isError: true };
    const { data: profile } = await supabase.from("profiles").select("name").eq("user_id", userId).maybeSingle();
    const { data: existing } = await supabase.from("bookings").select("id").eq("karigar_id", karigar_id).eq("date", date).eq("time", time).neq("status", "cancelled").maybeSingle();
    if (existing) {
      return { content: [{ type: "text", text: "That slot is already booked for this karigar." }], isError: true };
    }
    const { data, error } = await supabase.from("bookings").insert({
      customer_id: userId,
      customer_name: profile?.name ?? ctx.getUserEmail() ?? "Customer",
      karigar_id: karigar.id,
      karigar_name: karigar.name,
      skill: karigar.skill,
      date,
      time,
      description: description ?? null,
      status: "pending"
    }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/tools/cancel-booking.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var cancel_booking_default = defineTool4({
  name: "cancel_booking",
  title: "Cancel booking",
  description: "Cancel one of the signed-in user's bookings by id.",
  inputSchema: {
    booking_id: z4.string().describe("The booking id to cancel.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: false },
  handler: async ({ booking_id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bookings").update({ status: "cancelled" }).eq("id", booking_id).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "Booking not found or not accessible." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { booking: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's KarigarHub profile, and their karigar listing if they are a karigar.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: profile, error } = await supabase.from("profiles").select("name,email,phone,location,role").eq("user_id", userId).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const { data: karigar } = await supabase.from("karigars").select("id,name,skill,location,price,rating,review_count,availability,completed_jobs,total_earnings").eq("user_id", userId).maybeSingle();
    const result = { profile: profile ?? null, karigar: karigar ?? null };
    return {
      content: [{ type: "text", text: JSON.stringify(result) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rfqcfsdnlamimmohuwhg";
var mcp_default = defineMcp({
  name: "karigar-connect",
  title: "Karigar Connect",
  version: "0.1.0",
  instructions: "Tools for KarigarHub, an Indian local services marketplace connecting customers with skilled workers (karigars). Use `search_karigars` to find workers by skill/location/price, `create_booking` to request a job, `list_my_bookings` to review the signed-in user's bookings, `cancel_booking` to cancel one, and `get_my_profile` for the user's account details. All dates and times are Indian Standard Time.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    search_karigars_default,
    list_my_bookings_default,
    create_booking_default,
    cancel_booking_default,
    get_my_profile_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
